# Generated by Django 4.0.3 on 2022-07-09 09:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('tax_number', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^[0-9]{8}$')])),
            ],
        ),
    ]
