# Generated by Django 4.0.3 on 2022-07-13 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_organizationuser_delete_organizationadmin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationuser',
            old_name='admin',
            new_name='user',
        ),
    ]
