# Generated by Django 4.0.3 on 2022-07-13 13:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_rename_admin_organizationuser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='mobile_number',
            field=models.CharField(max_length=8, null=True, validators=[django.core.validators.RegexValidator('00|\\+386[0-9]{8}')]),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
